### ISSUE TITLE
Unmet dependency error during set up

### ISSUE THREAD

**Issue by rob-howells** [accessdigital/wilson#35]
Not sure if this is the best place to post this, however I'm encountering the following issue when trying to set up a new site using Wilson.

**Issue**

When following the steps in the project readme to create a new site using Wilson, I'm encountering the following error during step 6 (_Run the Drupal installer wizard..._) of the set up process:

<img width="938" alt="Screenshot 2022-09-21 at 16 34 27" src="https://user-images.githubusercontent.com/84845359/191547813-ba9ff4a0-5f81-411e-9986-38f1e0aaef08.png">

**Steps to reproduce**

Initialise a new site set up and work through the steps in the readme

**Additional information**

Local composer version 2.0.14

**Comment by AccessPaul** [comment]
I can't get my head round exactly why this error occurred but it appears to have cleared up in the latest version of Wilson. Try again with the new 1.10.1 version.

**Comment by iamsophiesk** [comment]
Was talking about this with Craig last night - IIRC one of the "big" modules that required CTools no longer requires it (Metatag? Redirect? Something like that). It needs to be included and enabled separately now because that module won't enable it anymore. 

Not sure if you've fixed it (I haven't tried the latest release) but just thought I'd let you know :)
